# Synthetic long data.frame shared across tests.
#
# Schema matches get_stock() output: Date, Symbol, Column, Value.
# Values are generated by a deterministic random walk (with seed) so the
# data resembles real OHLCV qualitatively without hitting the network.

make_long_df <- function(symbols = c("AAA", "BBB"),
                         columns = c("Open", "High", "Low", "Close", "Volume"),
                         n_days  = 80,
                         start   = as.Date("2024-01-01"),
                         seed    = 1L) {
  set.seed(seed)
  dates <- seq(start, by = "day", length.out = n_days)

  rows <- list()
  for (sym in symbols) {
    base   <- runif(1, 50, 200)
    closes <- round(base + cumsum(rnorm(n_days, 0, 1)), 2)
    for (col in columns) {
      values <- switch(col,
        Open   = closes + round(rnorm(n_days, 0, 0.3), 2),
        High   = closes + abs(round(rnorm(n_days, 0, 0.5), 2)),
        Low    = closes - abs(round(rnorm(n_days, 0, 0.5), 2)),
        Close  = closes,
        Adjusted = closes,
        Volume = round(runif(n_days, 1e5, 1e7))
      )
      rows[[length(rows) + 1L]] <- data.frame(
        Date   = dates,
        Symbol = sym,
        Column = col,
        Value  = values,
        stringsAsFactors = FALSE
      )
    }
  }
  do.call(rbind, rows)
}
