#' Get Index Components from Wikipedia
#'
#' Scrapes Wikipedia to retrieve the component list of a specified stock market index.
#' Currently supports the Dow Jones Industrial Average (DJI) and S&P 500.
#'
#' @param index A character string specifying the index. Must be either "DJI" or "SP500". Default is "DJI".
#'
#' @return A data.frame containing the index components with columns:
#'   \code{Symbol}, \code{Company}, \code{Industry}, and \code{Date_Added}.
#' @export
#'
#' @examples
#' \dontrun{
#' dji_components <- get_index_components("DJI")
#' sp500_components <- get_index_components("SP500")
#' }
get_index_components <- function(index = "DJI") {
  
  if (index == "DJI") {
    url <- "https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average"
  } else if (index == "SP500") {
    url <- "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
  } else {
    stop("Invalid index provided. Please use 'DJI' or 'SP500'.")
  }
  
  page <- rvest::read_html(url)
  tables <- rvest::html_table(page)
  
  # Dynamically find the table containing the "Symbol" column
  df <- NULL
  for (tbl in tables) {
    if (any(grepl("Symbol", colnames(tbl), ignore.case = TRUE))) {
      df <- tbl
      break
    }
  }
  
  if (is.null(df)) {
    stop(paste("Could not find the components table for", index, "on Wikipedia."))
  }
  
  # Dynamically find column names to prevent errors when Wikipedia updates headers
  col_names <- colnames(df)
  col_symbol <- grep("Symbol", col_names, ignore.case = TRUE, value = TRUE)[1]
  col_company <- grep("Company|Security", col_names, ignore.case = TRUE, value = TRUE)[1]
  col_industry <- grep("Industry|Sector", col_names, ignore.case = TRUE, value = TRUE)[1]
  col_date <- grep("Date added|Added", col_names, ignore.case = TRUE, value = TRUE)[1]
  
  # Select and standardize column names
  df <- df |>
    dplyr::select(
      Symbol = dplyr::all_of(col_symbol),
      Company = dplyr::all_of(col_company),
      Industry = dplyr::all_of(col_industry),
      Date_Added = dplyr::all_of(col_date)
    )
  
  # Clean the Date_Added column to remove Wikipedia footnote citations (e.g., "2020-08-31[12]")
  df$Date_Added <- stringr::str_extract(as.character(df$Date_Added), "^[0-9]{4}-[0-9]{2}-[0-9]{2}") |>
    anytime::anydate()
  
  # Ensure Symbol is character type
  df$Symbol <- as.character(df$Symbol)
  
  return(as.data.frame(df))
}


#' Sample Random Symbols from Components
#'
#' Selects a specified number of random stock symbols from the components data.frame.
#'
#' @param components A data.frame generated by \code{get_index_components()}.
#' @param n An integer specifying the number of symbols to randomly sample. Default is 3.
#' @param seed An optional integer to pass to \code{set.seed()} for reproducibility. Default is NULL.
#'
#' @return A character vector of sampled ticker symbols.
#' @export
#'
#' @examples
#' \dontrun{
#' comps <- get_index_components("DJI")
#' symbols <- sample_symbols(comps, n = 5, seed = 42)
#' }
sample_symbols <- function(components, n = 3, seed = NULL) {
  
  if (!is.null(seed)) {
    set.seed(seed)
  }
  
  if (!"Symbol" %in% colnames(components)) {
    stop("The provided components data.frame must contain a 'Symbol' column.")
  }
  
  sampled_symbols <- components$Symbol |>
    sample(size = min(n, nrow(components)))
  
  return(as.character(sampled_symbols))
}


#' Fetch Stock Data from Yahoo or Google Finance
#'
#' Retrieves historical OHLCV data for a given set of ticker symbols and formats
#' the output into a strict long-format data.frame to facilitate ggplot2 faceting.
#'
#' @param symbols A character vector of stock ticker symbols.
#' @param start A character string indicating the start date ("YYYY-MM-DD"). Default is "2020-01-01".
#' @param end A character string or Date object indicating the end date. Default is \code{Sys.Date()}.
#' @param columns A character vector specifying which columns to keep. Valid options: 
#'   "Open", "High", "Low", "Close", "Volume", "Adjusted". Default is \code{c("Close")}.
#' @param source A character string specifying the data source. Either "yahoo" or "google". Default is "yahoo".
#'
#' @return A data.frame in long format with columns: \code{Date}, \code{Symbol}, \code{Column}, \code{Value}.
#' @export
#'
#' @examples
#' \dontrun{
#' raw_data <- get_stock(
#'   symbols = c("AAPL", "MSFT"), 
#'   start = "2022-01-01", 
#'   columns = c("Close", "Volume")
#' )
#' }
get_stock <- function(symbols, start = "2020-01-01", end = Sys.Date(), columns = c("Close"), source = "yahoo") {
  
  # Validate and parse dates using stringr and anytime
  start_parsed <- stringr::str_trim(as.character(start)) |> anytime::anydate()
  end_parsed <- stringr::str_trim(as.character(end)) |> anytime::anydate()
  
  if (is.na(start_parsed) || is.na(end_parsed)) {
    stop("Invalid date format detected. Please use 'YYYY-MM-DD'.")
  }
  
  # Ensure the source is valid
  if (!source %in% c("yahoo", "google")) {
    stop("Invalid source. Please specify either 'yahoo' or 'google'.")
  }
  
  results_list <- list()
  
  for (sym in symbols) {
    tmp_env <- new.env()
    
    # Attempt to fetch data; suppress warnings for cleaner terminal output
    fetch_success <- tryCatch({
      quantmod::getSymbols(
        Symbols = sym, 
        env = tmp_env, 
        src = source, 
        from = start_parsed, 
        to = end_parsed, 
        warnings = FALSE, 
        auto.assign = TRUE
      )
      TRUE
    }, error = function(e) {
      warning(paste("Failed to fetch data for symbol:", sym, "- Skipping."))
      FALSE
    })
    
    if (fetch_success) {
      raw_xts <- tmp_env[[sym]]
      df <- as.data.frame(raw_xts)
      df$Date <- as.Date(rownames(df))
      rownames(df) <- NULL
      
      # Strip the ticker prefix from column names (e.g., "AAPL.Close" -> "Close")
      colnames(df) <- gsub(paste0("^", sym, "\\."), "", colnames(df))
      
      # Filter for requested columns safely
      keep_cols <- intersect(columns, colnames(df))
      
      if (length(keep_cols) == 0) {
        warning(paste("None of the requested columns were found for symbol:", sym))
        next
      }
      
      df <- df[, c("Date", keep_cols), drop = FALSE]
      df$Symbol <- sym
      
      # Convert to strict LONG FORMAT using tidyr
      df_long <- df |>
        tidyr::pivot_longer(
          cols = dplyr::all_of(keep_cols),
          names_to = "Column",
          values_to = "Value"
        )
      
      results_list[[sym]] <- df_long
    }
  }
  
  if (length(results_list) == 0) {
    stop("Failed to fetch data for all provided symbols.")
  }
  
  # Combine all lists into a single long data.frame
  final_df <- dplyr::bind_rows(results_list) |>
    dplyr::arrange(Date, Symbol, Column)
  
  return(as.data.frame(final_df))
}